name : build
on: push
jobs:
 test:
  runs-on: ubuntu-latest
  steps :
   - name: copie code depuis github vers ubuntu
     uses: actions/checkout@v3
   - name: installer NODEJS sur ubuntu 
     uses: actions/setup-node@v3
   - name: installer des packages JS
     run: npm install
   - name: build app JS
     run: npm run build

 build:
  runs-on: ubuntu-latest
  needs: test 
  steps :
   - name: copie code depuis github vers ubuntu
     uses: actions/checkout@v3
   - name: installer NODEJS sur ubuntu 
     uses: actions/setup-node@v3
   - name: installer des packages JS
     run: npm install
   - name: build app JS
     run: npm run build


   
   
